### ISSUE TITLE
FbShare

### ISSUE THREAD

**Issue by dipaktandel** [webaddicted/EasySocialLogin#1]
On FbShare  -   image shared successfully. but postID always return null .

i wanted postID. can you help me to solve this issue.

**Comment by webaddicted** [comment]
now you can get post id by implement FbPostListener .

**Comment by dipaktandel** [comment]
Thank you so much webaddicted  for your answer.

it would be  very helpful for me if you give me an example or any document link.

**Comment by webaddicted** [comment]
Which type of document link do you need
